import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// ============================================================================
// COMPLETE METHODOLOGY SOURCE DATA - Nechama Yaffe's Color Analysis System
// This is the definitive source of truth for all subtypes
// ============================================================================

interface JewelryInfo {
  metals?: { perfect?: string[]; good?: string[]; avoid?: string[] };
  stones?: { perfect?: string[]; good?: string[]; avoid?: string[] };
  styles?: string[];
}

interface SubtypeData {
  slug: string;
  name: string;
  season: string;
  time_period?: string;
  description?: string;
  palette_effect?: string;
  key_colors: string[];
  avoid_colors: string[];
  fabrics_perfect: string[];
  fabrics_good: string[];
  fabrics_avoid: string[];
  prints: string[];
  silhouettes: string[];
  jewelry_metals: string[];
  jewelry_stones: string[];
  jewelry_styles: string[];
  eras: string[];
  artists: string[];
  designers: string[];
  makeup_lip: string[];
  makeup_cheek: string[];
  makeup_eye: string[];
  best_for: string[];
}

// Complete subtype definitions from the methodology
const METHODOLOGY_SUBTYPES: SubtypeData[] = [
  // ==================== SPRING ====================
  {
    slug: "wildflower-spring",
    name: "Wildflower Spring",
    season: "spring",
    time_period: "early",
    description: "Delicate, romantic, whimsical Spring with Dutch master sensibility",
    palette_effect: "Girl with a Pearl Earring",
    key_colors: ["Blush", "Rose", "Pink", "Coral", "Peach", "Caramel", "Golden Brown", "Indigo", "Navy", "Kelly Green", "Seafoam", "Periwinkle"],
    avoid_colors: [],
    fabrics_perfect: ["Tulle Trim", "Ruched Fabric", "Embroidery", "Appliqué", "Crocheted Lace", "Eyelet"],
    fabrics_good: ["Paisley", "Suede", "Velvet", "Small Tweeds", "Gingham", "Patchwork"],
    fabrics_avoid: [],
    prints: ["Florals", "Butterflies", "Whimsical Prints", "Dutch Knits", "Trompe L'oeil"],
    silhouettes: ["Romantic layers", "Whimsical accessories", "Soft textures"],
    jewelry_metals: ["Gold", "Silver"],
    jewelry_stones: ["Pearl", "Blue Topaz", "Amethyst"],
    jewelry_styles: ["Enamel", "Cloisonné", "Wildflowers", "Whimsical Charms", "Clover", "Celtic Knots", "Pearls", "Fleur-de-lis"],
    eras: ["1600s Dutch", "Rembrandt and Vermeer", "1700s French Romantic", "1930s Europe"],
    artists: ["Vermeer", "Rembrandt", "Van Gogh", "Degas"],
    designers: ["Miu Miu", "Marni", "Chanel"],
    makeup_lip: ["Coral", "Soft Pink"],
    makeup_cheek: ["Soft Pink", "Coral"],
    makeup_eye: ["Blue-Green", "Purple"],
    best_for: ["Romantic occasions", "Garden parties", "Artistic events"],
  },
  {
    slug: "french-spring",
    name: "French Spring",
    season: "spring",
    time_period: "mid",
    description: "French elegance with garden florals and refined femininity",
    palette_effect: "Gardenia Summer",
    key_colors: ["Geranium Pink", "Ballet Pink", "Coral Pink", "Rose Pink", "Midnight Blue", "Navy", "Soft Chocolate", "Lavender", "Violet", "Robin's Egg Blue"],
    avoid_colors: ["Amber", "Orange", "Heavy gold tones"],
    fabrics_perfect: ["Organza", "Muslin", "Cotton", "Taffeta", "Fine Tweed", "Cotton lace"],
    fabrics_good: ["Velvet", "Grosgrain Ribbons", "Linen/Cotton", "Denim", "Chambray", "Wool Jersey", "Angora", "Suede"],
    fabrics_avoid: [],
    prints: ["Gardenias", "Dogwood", "Jasmine", "Small Roses", "Butterflies", "Fleur De Lis", "Delftware", "Porcelain Tiles"],
    silhouettes: ["Lacing on dresses", "Peasant style", "Dirndl Skirt"],
    jewelry_metals: ["Rose Gold", "Silver"],
    jewelry_stones: ["Green Glass", "Blue Topaz", "Sapphire", "Pink Coral", "White Coral", "Amethyst"],
    jewelry_styles: ["Enameled Jewelry", "Floral Jewels", "Clusters of Stones", "Velvet Ribbons for Necklaces"],
    eras: ["1800's French Dress", "1800's Dutch", "Gibson Girl", "Japanese Kimono"],
    artists: ["Mary Cassatt", "Renoir", "Odilon Redon"],
    designers: [],
    makeup_lip: ["Coral", "Soft Pink"],
    makeup_cheek: ["Soft Pink", "Coral"],
    makeup_eye: ["Blue-Green", "Purple"],
    best_for: ["Elegant occasions", "French-inspired events"],
  },
  {
    slug: "early-spring",
    name: "Early Spring",
    season: "spring",
    time_period: "early",
    description: "The first delicate touches of Spring - soft, fresh, awakening",
    palette_effect: "Cherry Blossoms",
    key_colors: ["Soft Pink", "Blush", "Peach", "Cream", "Rose", "Dusty Mauve", "Teal", "Seafoam", "Lavender"],
    avoid_colors: [],
    fabrics_perfect: ["Silk", "Fine Cotton", "Chiffon", "Cashmere"],
    fabrics_good: ["Fine Knit", "Crêpe", "Eyelet"],
    fabrics_avoid: [],
    prints: ["Cherry Blossoms", "Seashells", "Butterflies", "Delicate Florals", "Birds", "First Flowers"],
    silhouettes: ["Delicate layers", "Soft textures"],
    jewelry_metals: ["Rose Gold", "Silver"],
    jewelry_stones: ["Aquamarine", "Rose Quartz", "Pearl", "Blue Topaz"],
    jewelry_styles: ["Delicate chains", "Floral motifs"],
    eras: ["Edwardian", "Early 1900s", "French Romantic"],
    artists: [],
    designers: [],
    makeup_lip: ["Soft Pink", "Rose"],
    makeup_cheek: ["Soft Pink"],
    makeup_eye: ["Teal", "Aquamarine"],
    best_for: ["Fresh beginnings", "Romantic occasions"],
  },

  // ==================== SUMMER ====================
  {
    slug: "ballerina-summer",
    name: "Ballerina Summer",
    season: "summer",
    time_period: "early",
    description: "Princess-like elegance with rose garden softness and classical grace",
    palette_effect: "Swan Lake",
    key_colors: ["Rose", "Dusty Rose", "Cream", "Navy Blue", "Midnight Blue", "Slate Blue", "Dark Emerald", "Lavender", "Lilac"],
    avoid_colors: ["Amber", "Orange", "Dark heavy stones"],
    fabrics_perfect: ["Lace", "Eyelet", "White Fur", "Fine Cotton", "Organza", "Chiffon"],
    fabrics_good: ["Embroidery", "Needlepoint", "Fine wool", "Wool Jersey", "Velvet", "Fine Corduroy"],
    fabrics_avoid: [],
    prints: ["Florals", "Roses", "Hydrangeas", "Tulips", "Violets", "Paisley", "Polka Dots", "Hearts", "Ribbons"],
    silhouettes: ["A line Skirts", "Princess cut dress or coat", "Butterfly Sleeve", "Ruffled Sleeve"],
    jewelry_metals: ["Rose Gold", "Silver"],
    jewelry_stones: ["Amethyst", "Blue topaz", "Green opals", "Pearls", "Quartz"],
    jewelry_styles: ["Colored stones", "Enamel Flowers", "Hanging beaded earrings", "Cameo Flowers"],
    eras: ["Gibson Girl", "England 1800's", "France 1800's", "Hungarian Costume 19th century"],
    artists: ["Monet", "Cassatt"],
    designers: [],
    makeup_lip: ["Rose", "Cherry red", "Cream"],
    makeup_cheek: ["Rose", "Pink"],
    makeup_eye: ["Emerald", "Silver", "Gold", "Rose"],
    best_for: ["Ballet performances", "Romantic events", "Classical occasions"],
  },
  {
    slug: "cameo-summer",
    name: "Cameo Summer",
    season: "summer",
    time_period: "mid",
    description: "Victorian elegance with cameo-inspired romantic softness",
    palette_effect: "English Roses",
    key_colors: ["Cream", "Peach", "Rose", "Dark Rose", "Claret", "Purple", "Slate Blue", "Blue Green", "Aqua", "Lavender", "Seafoam"],
    avoid_colors: [],
    fabrics_perfect: ["Toile", "Embroidered Cotton", "Velvet", "Chiffon", "Smooth Satin"],
    fabrics_good: ["Micro Tweeds", "Fine Wool", "Cotton Linen Mix", "Suede", "Jersey", "Satin Jersey"],
    fabrics_avoid: [],
    prints: [],
    silhouettes: ["S-curve", "Feathers and Lace", "Delicate Ties and Ribbon"],
    jewelry_metals: ["Rose Gold", "Silver"],
    jewelry_stones: ["Cameos", "Pink Quartz", "Pearls", "Rubies", "Sapphires", "Labradorite"],
    jewelry_styles: ["Dangling Earrings", "Teardrop earrings", "Pear Cut Pink Diamond"],
    eras: [],
    artists: [],
    designers: [],
    makeup_lip: ["Reds", "Rose"],
    makeup_cheek: ["Cameo", "Pale Pink"],
    makeup_eye: ["Blue Green"],
    best_for: ["Victorian-inspired events", "Romantic occasions"],
  },
  {
    slug: "chinoiserie-summer",
    name: "Chinoiserie Summer",
    season: "summer",
    time_period: "mid",
    description: "Oriental elegance with Japanese garden and chinoiserie influences",
    palette_effect: "Summer Princess",
    key_colors: ["Rose", "Apricot Rose", "Dusty Rose", "Dark Blue", "Hunter Green", "Chocolate Brown", "Olive Green", "Burgundy", "Sapphire Blue", "Teal"],
    avoid_colors: [],
    fabrics_perfect: ["Lace", "Crocheted lace", "Eyelet", "Velvet", "Crushed Velvet"],
    fabrics_good: ["Corduroy", "Chambray", "Denim", "Soft Leather", "Suede", "Fine Tweed", "Brocade", "Tapestry", "Silk"],
    fabrics_avoid: [],
    prints: ["Roses", "Myrtle", "Clematis", "Wisteria", "Wild Rose", "Camelias", "Star Flowers", "Butterflies", "Dragonflies"],
    silhouettes: ["A Line dresses", "Safari dress", "Kimono dress", "Wrap dresses", "Grecian style"],
    jewelry_metals: ["Rose Gold", "Gold", "Silver"],
    jewelry_stones: ["Blue Topaz", "Aquamarine", "Labradorite", "Pink Quartz", "Opals", "Amethyst", "Garnet"],
    jewelry_styles: ["Enamel", "Cloisonne", "Filigree", "Cameos in Roses and Leaves", "Birds and Feathers"],
    eras: [],
    artists: ["Sargent", "Degas"],
    designers: ["Bluemarine", "Chloe"],
    makeup_lip: ["Roses", "Apricots"],
    makeup_cheek: ["Soft Pink", "Apricot"],
    makeup_eye: ["Blues", "Teals"],
    best_for: ["Oriental-inspired events", "Garden parties"],
  },
  {
    slug: "degas-summer",
    name: "Degas Summer",
    season: "summer",
    time_period: "mid",
    description: "Impressionist palette with soft opalescent and moonstone colors",
    palette_effect: "Opal and Moonstone Palette",
    key_colors: ["Mushroom", "Taupe", "Mauve", "Pink Mauve", "Silver", "Pistachio", "Apricot", "Soft Purple", "Lilac", "Deep Purple", "Cadet Blue", "Deep teal", "Seafoam"],
    avoid_colors: [],
    fabrics_perfect: ["Velvet", "Soft knits", "Chanel Tweed", "Fine corduroy"],
    fabrics_good: ["Jersey", "Silk", "Tulle", "Eyelet", "Crocheted Lace", "Angora", "Mohair", "Soft Leather", "Suede"],
    fabrics_avoid: [],
    prints: ["Small flowers", "Stripes", "Animal print", "Tulips", "Peonies", "Bluebells", "Hibiscus", "Jasmine"],
    silhouettes: ["A-line dress", "Fitted top with Flowy skirt", "Puffed sleeve", "Mutton sleeve"],
    jewelry_metals: ["Rose Gold", "Silver"],
    jewelry_stones: ["Garnet", "Rhodonite", "Quartz", "Moonstone", "Opal", "Blue Topaz", "Agate", "Tourmaline"],
    jewelry_styles: ["Beaded Chandelier Earrings", "Tear Drop shapes", "Multi colored gemstones"],
    eras: [],
    artists: ["Ingres", "Vermeer"],
    designers: ["Marni", "Bluemarine", "Chloe"],
    makeup_lip: ["Mauves", "Pink"],
    makeup_cheek: ["Soft Pink"],
    makeup_eye: ["Iridescent Mauves", "Pink and Green"],
    best_for: ["Artistic events", "Impressionist-inspired occasions"],
  },
  {
    slug: "emerald-summer",
    name: "Emerald Summer",
    season: "summer",
    time_period: "mid",
    description: "Renaissance princess with tea rose and emerald palette",
    palette_effect: "Rose Garden",
    key_colors: ["Cameo", "Rose", "Terra Cotta-Rose", "Soft Wine", "Burgundy", "Midnight", "Navy", "Golden Brown", "Blue-Purples", "Bottle Green", "Emerald"],
    avoid_colors: [],
    fabrics_perfect: ["Crocheted Lace", "Fine Lace", "Velvet", "Corduroy"],
    fabrics_good: ["Striped Denim", "Fine Wool", "Fine Tweed", "Embossed Floral Leather", "Suede", "Silk", "Organza", "Chiffon"],
    fabrics_avoid: [],
    prints: ["Antique Roses", "Tea Roses", "Birds", "Flowers", "Butterflies", "Polka dots", "Paisley", "Tile Mosaic"],
    silhouettes: ["Princess cut", "Military braided jacket", "Belted dresses", "Safari style"],
    jewelry_metals: ["Copper", "Rose Gold", "White Gold"],
    jewelry_stones: ["Emeralds", "Small diamonds", "Topaz", "Blue Topaz"],
    jewelry_styles: ["Cameos", "Enamel flowers and leaves", "Floral filigree", "Pearls"],
    eras: ["English Renaissance", "French 1800's", "England 1800's", "Gibson Girl", "1940's fashion"],
    artists: ["John Singer Sargent", "Dante Gabriel Rossetti"],
    designers: [],
    makeup_lip: ["Rose", "Burgundy"],
    makeup_cheek: ["Rose"],
    makeup_eye: ["Emerald", "Blue"],
    best_for: ["Renaissance events", "Elegant occasions"],
  },
  {
    slug: "porcelain-summer",
    name: "Porcelain Summer",
    season: "summer",
    time_period: "mid",
    description: "Deep Sapphire Blues and Glass Greens. Light pinks and blues of flowers grounded with Golden Browns. A pure and iridescent Palette",
    palette_effect: "Porcelain effect",
    key_colors: ["Rose", "Rose Mauve", "Cream", "Ivory", "Mauve-Red", "Plum", "Midnight Blue", "Navy", "Taupe", "Blue Greens", "Teal", "Emerald", "Sapphire Blue", "Lavender", "Periwinkle"],
    avoid_colors: [],
    fabrics_perfect: ["Fine Lace", "Eyelet", "Crocheted Lace", "Net", "Chiffon", "Tulle"],
    fabrics_good: ["Tweed", "Velvet", "Crushed velvet", "Corduroy", "Chambray", "Denim", "Fine wool", "Silk", "Iridescent fabric"],
    fabrics_avoid: [],
    prints: ["Roses", "Daisies", "Anemones", "Peonies", "Water Lilies", "Blue and White China", "Cherry Blossoms", "Toile Prints"],
    silhouettes: ["A line Dresses", "Princess Cut dresses", "Military style", "Grecian pleated dress"],
    jewelry_metals: ["Gold", "Silver"],
    jewelry_stones: ["Amethyst", "Blue topaz", "Topaz", "Garnet", "Quartz", "Pearls", "Sapphires", "Green Glass"],
    jewelry_styles: ["Enamel designs", "Cameos", "Cloisonne", "Jeweled flowers", "Bird Pendants", "Filigree"],
    eras: ["Edwardian", "French 1700's", "Russian Princess 1800's"],
    artists: ["Degas", "Sargent"],
    designers: [],
    makeup_lip: ["Deep Rose", "Dusty red"],
    makeup_cheek: ["Rose", "Pink"],
    makeup_eye: ["Emerald", "Blue"],
    best_for: ["Formal events", "Porcelain-inspired occasions"],
  },
  {
    slug: "summer-rose",
    name: "Summer Rose",
    season: "summer",
    time_period: "mid",
    description: "A Watercolor Palette in Blues, Greens and Purples. The Golden-Browns and Creams add warmth to the pastels. A Palette of a Rose Garden in late Summer",
    palette_effect: "Summer Rose Garden",
    key_colors: ["Rose", "Apricot", "Cream", "Dark Rose", "Soft red", "Navy Blue", "Midnight Blue", "Golden Brown", "Mushroom", "Emerald", "Sapphire", "Lavender", "Chartreuse"],
    avoid_colors: [],
    fabrics_perfect: ["Eyelet", "Lace", "Crocheted Lace", "Velvet", "Crushed Velvet"],
    fabrics_good: ["Fine Corduroy", "Chambray", "Denim", "Organza", "Chiffon", "Tulle", "Tweed", "Silk", "Suede"],
    fabrics_avoid: [],
    prints: ["Flowers", "Ribbons", "Pearls", "Birds", "Butterflies", "Roses", "Peonies", "Tulips", "Water Lilies", "Lotus", "Cherry Blossoms"],
    silhouettes: ["Garden Fairy", "Cowgirl Style", "Milk Maiden", "English Rose", "Sailor Chic"],
    jewelry_metals: ["Rose Gold", "Silver", "Gold"],
    jewelry_stones: ["Amethyst", "Blue topaz", "Emerald", "Pearls", "Opals", "Pink Coral"],
    jewelry_styles: ["Hearts", "Lockets", "Ribbons", "Cameos", "Pearls in Gold settings"],
    eras: ["English 1800's", "Edwardian", "Gibson Girl"],
    artists: ["Monet", "Renoir"],
    designers: ["Chloe", "Ulla Johnson"],
    makeup_lip: ["Rose", "Red"],
    makeup_cheek: ["Rose", "Pink"],
    makeup_eye: ["Emerald", "Teal"],
    best_for: ["Rose garden events", "Summer occasions"],
  },

  // ==================== AUTUMN ====================
  {
    slug: "auburn-autumn",
    name: "Auburn Autumn",
    season: "autumn",
    time_period: "early",
    description: "Celtic fire with warm auburn tones and earthy elegance",
    palette_effect: "Celtic Fire",
    key_colors: ["Terra Cotta", "Soft Peach", "Apricot", "Cream", "Burgundy", "Wine", "Dark Rust", "Black", "Midnight Blue", "Chocolate", "Auburn", "Olive", "Emerald", "Teal"],
    avoid_colors: [],
    fabrics_perfect: ["Tweed", "Wool", "Cashmere", "Leather", "Suede"],
    fabrics_good: ["Velvet", "Corduroy", "Denim", "Linen", "Silk Shantung"],
    fabrics_avoid: [],
    prints: ["Paisley", "Plaid", "Herringbone", "Leaves", "Celtic patterns"],
    silhouettes: ["Tailored", "Riding style", "Classic cuts"],
    jewelry_metals: ["Copper", "Antique Gold", "Bronze"],
    jewelry_stones: ["Amber", "Topaz", "Emerald", "Jade", "Coral"],
    jewelry_styles: ["Celtic knots", "Leaves", "Organic shapes"],
    eras: ["Celtic", "Victorian", "1940's"],
    artists: ["Pre-Raphaelites"],
    designers: ["Ralph Lauren"],
    makeup_lip: ["Burgundy", "Wine", "Rust"],
    makeup_cheek: ["Terracotta", "Peach"],
    makeup_eye: ["Bronze", "Copper", "Olive"],
    best_for: ["Autumn events", "Celtic-inspired occasions"],
  },
  {
    slug: "mellow-autumn",
    name: "Mellow Autumn",
    season: "autumn",
    time_period: "mid",
    description: "Grecian Princess with Mediterranean palette of end of autumn",
    palette_effect: "Grecian Princess",
    key_colors: ["Terra Cotta", "Apricot", "Soft Coral", "Cream", "Burgundy", "Maroon", "Black", "Prussian Blue", "Mushrooms", "Charcoals", "Olive", "Dark Teal", "Bright Teal", "Emerald"],
    avoid_colors: [],
    fabrics_perfect: ["Denim", "Fur", "Mohair", "Tweed", "Leather", "Suede"],
    fabrics_good: ["Shantung", "Chiffon", "Velvet", "Brocade", "Tapestry"],
    fabrics_avoid: [],
    prints: ["Paisley", "Herringbone", "Houndstooth", "Prince of Wales", "Leaves", "Moroccan Tile", "Animal print"],
    silhouettes: ["Tailored", "Classic", "Elegant drape"],
    jewelry_metals: ["Copper", "Antique Gold", "Pewter", "Yellow Gold"],
    jewelry_stones: ["Topaz", "Emerald", "Amber", "Citrine", "Labradorite", "Pearls", "Coral", "Jade", "Ivory"],
    jewelry_styles: ["Braided gold", "Chain link", "Rope necklaces", "Leaves", "Coins", "Feathers", "Filigree"],
    eras: ["19th Century Morocco", "19th Century Spain and Italy", "1940's", "1920's Art Deco"],
    artists: ["Modigliani", "Corot"],
    designers: ["Etro", "Cuccinelli", "Ralph Lauren"],
    makeup_lip: ["Terracotta", "Burgundy"],
    makeup_cheek: ["Terracotta", "Peach"],
    makeup_eye: ["Bronze", "Olive", "Teal"],
    best_for: ["Mediterranean events", "Autumn occasions"],
  },
  {
    slug: "renaissance-autumn",
    name: "Renaissance Autumn",
    season: "autumn",
    time_period: "mid",
    description: "Renaissance Queen with Mediterranean and Medieval influences",
    palette_effect: "Renaissance Queen",
    key_colors: ["Terra Cotta", "Apricot", "Pink Terra Cotta", "Ecru", "Ivory", "Sangria", "Coral", "Midnight Blue", "Navy", "Charcoal", "Pewter", "Teal", "Dark Emeralds", "Aquamarine", "Cobalt"],
    avoid_colors: [],
    fabrics_perfect: ["Silk shantung", "Silk", "Satin", "Taffeta", "Velvet"],
    fabrics_good: ["Corduroy", "Denim", "Cashmere", "Pashmina", "Lace", "Sari silk", "Tapestries", "Tweed", "Leather", "Suede"],
    fabrics_avoid: [],
    prints: ["Printed chiffon of houses, Trees, Water", "Paisley", "Tiger, Zebra, leopard", "Houndstooth", "Burberry Plaid"],
    silhouettes: ["Renaissance lacing", "Cape like wraps", "Mandarin Collar"],
    jewelry_metals: ["Gold", "Pewter", "Copper", "Silver"],
    jewelry_stones: ["Pearls", "Shells", "Amber", "Topaz", "Jade", "Onyx", "Opals", "Blue Topaz"],
    jewelry_styles: ["Rope necklaces", "Chain links", "Indian and Persian designs", "Grapes, wheat, leaves motifs"],
    eras: ["Renaissance Italy", "Medieval Spain", "Persian", "Moroccan"],
    artists: ["John Singer Sargent"],
    designers: ["Etro", "Dries Van Noten"],
    makeup_lip: ["Coral", "Sangria"],
    makeup_cheek: ["Terracotta", "Apricot"],
    makeup_eye: ["Cobalt", "Teal", "Emerald"],
    best_for: ["Renaissance events", "Formal occasions"],
  },
  {
    slug: "sunlit-autumn",
    name: "Sunlit Autumn",
    season: "autumn",
    time_period: "early",
    description: "Like an Early September day. Leaves just changing, mix of flowers, fruits and leaves",
    palette_effect: "Sunlight in Early Autumn",
    key_colors: ["Terra Cotta", "Rose Terra Cotta", "Apricot", "Cream", "Sangria", "Red Brown", "Burgundy", "Black", "Midnight Blue", "Plum", "Olive", "Sea Green", "Emerald Green", "Bright blue", "Aqua"],
    avoid_colors: [],
    fabrics_perfect: ["Heavy lace", "Crocheted lace", "Fine lace", "Gold and Copper lace"],
    fabrics_good: ["Jersey wool", "Boucle", "Irish knits", "Tweed", "Velvet", "Brocade", "Denim", "Leather", "Suede", "Cashmere"],
    fabrics_avoid: [],
    prints: ["Leaves and Flowers", "Palm trees", "Wheat", "Plaid", "Herringbone", "Chevron", "Paisley", "Leopards", "Indian prints"],
    silhouettes: ["Grecian", "Mediterranean", "Egyptian"],
    jewelry_metals: ["Gold", "Antique gold", "Antique silver"],
    jewelry_stones: ["Emeralds", "Ivory", "Jade", "Blue Topaz", "Topaz", "Pearls", "Pink coral", "White coral"],
    jewelry_styles: ["Links", "Ropes and chains", "Birds, wings, feathers", "Tassels", "Egyptian motifs"],
    eras: ["1970's", "Classic Grecian", "Mediterranean", "Egyptian"],
    artists: ["Van Gogh", "Da Vinci"],
    designers: ["Cavalli", "Dries Van Noten", "Brunello Cuccinelli"],
    makeup_lip: ["Sangria", "Terracotta"],
    makeup_cheek: ["Terracotta", "Apricot"],
    makeup_eye: ["Gold", "Olive", "Teal"],
    best_for: ["Autumn celebrations", "Harvest events"],
  },
  {
    slug: "tapestry-autumn",
    name: "Tapestry Autumn",
    season: "autumn",
    time_period: "mid",
    description: "Spanish Sunset with Mediterranean and French influences",
    palette_effect: "Spanish Sunset",
    key_colors: ["Terra Cotta", "Soft Peach", "Ivory", "Cream", "Coral", "Soft Rust", "Midnight Blue", "Prussian Blue", "Olive", "Black Olive", "Burgundy", "Purple", "Emerald Green", "Cobalt Blue"],
    avoid_colors: [],
    fabrics_perfect: ["Silk Shantung", "Silk-Linen", "Linen-Cotton", "Denim"],
    fabrics_good: ["Fur", "Suede", "Velvet", "Satin", "Boucle", "Tweed", "Cashmere", "Tapestry", "Brocade"],
    fabrics_avoid: [],
    prints: ["Paisley", "Mosaic", "Tile patterns", "Spanish motifs", "Mediterranean prints", "Fruit and Vine", "Animal prints"],
    silhouettes: ["Mediterranean", "Spanish", "French Girl Chic"],
    jewelry_metals: ["Copper", "Bronze", "Antique Gold", "Pewter"],
    jewelry_stones: ["Coral", "Amber", "Topaz", "Jade", "Turquoise"],
    jewelry_styles: ["Mosaic designs", "Tapestry inspired", "Ethnic patterns", "Coins", "Links"],
    eras: ["Spanish Renaissance", "Mediterranean"],
    artists: ["Corot"],
    designers: ["Etro", "Missoni"],
    makeup_lip: ["Coral", "Rust"],
    makeup_cheek: ["Terracotta", "Peach"],
    makeup_eye: ["Cobalt", "Emerald"],
    best_for: ["Spanish-inspired events", "Mediterranean occasions"],
  },
  {
    slug: "topaz-autumn",
    name: "Topaz Autumn",
    season: "autumn",
    time_period: "late",
    description: "Autumn Jewels with golden harvest and Mediterranean autumn",
    palette_effect: "Autumn Jewels",
    key_colors: ["Terra Cotta", "Apricot", "Soft Peach", "Cream", "Ecru", "Burgundy", "Wine", "Coral", "Rust", "Midnight Blue", "Prussian Blue", "Olive", "Emerald", "Teal", "Cobalt", "Sapphire"],
    avoid_colors: [],
    fabrics_perfect: ["Silk Shantung", "Velvet", "Suede", "Leather"],
    fabrics_good: ["Tweed", "Cashmere", "Wool", "Brocade", "Satin", "Linen"],
    fabrics_avoid: [],
    prints: ["Paisley", "Leaves and Branches", "Geometric", "Animal prints", "Ethnic patterns", "Mosaic"],
    silhouettes: ["Tailored", "Classic", "Mediterranean"],
    jewelry_metals: ["Gold", "Antique Gold", "Copper", "Bronze"],
    jewelry_stones: ["Topaz", "Amber", "Citrine", "Yellow Sapphire", "Emerald", "Jade"],
    jewelry_styles: ["Links", "Chains", "Coins", "Leaves and Branches", "Ethnic designs"],
    eras: ["Mediterranean", "Spanish"],
    artists: ["Corot", "Modigliani"],
    designers: ["Etro", "Cavalli"],
    makeup_lip: ["Burgundy", "Wine"],
    makeup_cheek: ["Terracotta"],
    makeup_eye: ["Topaz", "Gold", "Emerald"],
    best_for: ["Autumn galas", "Jewel-toned events"],
  },

  // ==================== WINTER ====================
  {
    slug: "burnished-winter",
    name: "Burnished Winter",
    season: "winter",
    time_period: "mid",
    description: "Winter Sunset with Medieval Knight and Spanish Renaissance influences",
    palette_effect: "Winter Sunset",
    key_colors: ["Rose Terra Cotta", "Terra Cotta", "Apricot", "Cream", "Ivory", "Burgundy", "Wine", "Sangria", "Black", "Blue-Black", "Midnight Blue", "Charcoal", "Pewter", "Emerald", "Teal", "Cobalt Blue", "Sapphire"],
    avoid_colors: [],
    fabrics_perfect: ["Velvet", "Brocade", "Tapestry", "Silk Shantung", "Satin"],
    fabrics_good: ["Cashmere", "Fine Wool", "Leather", "Suede", "Tweed", "Lace", "Metallic Weave"],
    fabrics_avoid: [],
    prints: ["Paisley", "Brocade patterns", "Tapestry designs", "Herringbone", "Houndstooth", "Animal prints", "Medieval motifs"],
    silhouettes: ["Medieval Knight", "Spanish Renaissance", "Antique Tapestry"],
    jewelry_metals: ["Antique Gold", "Pewter", "Silver", "Platinum"],
    jewelry_stones: ["Emeralds", "Sapphires", "Rubies", "Topaz", "Amber", "Diamonds"],
    jewelry_styles: ["Links", "Chains", "Rope designs", "Medieval inspired", "Coins", "Filigree"],
    eras: ["Medieval", "Spanish Renaissance"],
    artists: [],
    designers: [],
    makeup_lip: ["Deep reds", "Burgundy"],
    makeup_cheek: ["Rose", "Terracotta"],
    makeup_eye: ["Emerald", "Sapphire", "Gold"],
    best_for: ["Medieval events", "Renaissance fairs", "Formal occasions"],
  },
  {
    slug: "cameo-winter",
    name: "Cameo Winter",
    season: "winter",
    time_period: "mid",
    description: "Cameo Portrait with Victorian Rose and Edwardian elegance",
    palette_effect: "Cameo Portrait",
    key_colors: ["Rose", "Pink Rose", "Cameo Pink", "Cream", "Porcelain", "Wine", "Burgundy", "Deep Rose", "Black", "Navy Blue", "Midnight Blue", "Silver Grey", "Pewter", "Emerald", "Teal", "Sapphire", "Cobalt", "Lavender", "Ice Blue"],
    avoid_colors: [],
    fabrics_perfect: ["Velvet", "Satin", "Fine Lace", "Chiffon", "Silk"],
    fabrics_good: ["Cashmere", "Fine Wool", "Brocade", "Organza"],
    fabrics_avoid: [],
    prints: ["Cameos", "Roses", "Victorian florals", "Lace patterns", "Fine stripes", "Ribbons", "Pearls"],
    silhouettes: ["Victorian Rose", "Edwardian Elegance", "Winter Rose Garden"],
    jewelry_metals: ["Silver", "White Gold", "Platinum", "Rose Gold"],
    jewelry_stones: ["Cameos", "Pearls", "Sapphires", "Diamonds", "Amethyst", "Blue Topaz"],
    jewelry_styles: ["Cameos", "Filigree", "Victorian designs", "Delicate chains", "Pearl strands", "Lockets"],
    eras: ["Victorian", "Edwardian"],
    artists: [],
    designers: [],
    makeup_lip: ["Deep wine", "Rose"],
    makeup_cheek: ["Rose", "Cream"],
    makeup_eye: ["Sapphire", "Soft grey"],
    best_for: ["Victorian events", "Formal occasions", "Romantic events"],
  },
  {
    slug: "crystal-winter",
    name: "Crystal Winter",
    season: "winter",
    time_period: "early",
    description: "Ice Crystal with Winter Forest and frozen lake palette",
    palette_effect: "Ice Crystal",
    key_colors: ["Ice-Pink", "Silver-Pink", "Rose", "Cream", "Porcelain", "Deep Rose", "Raspberry", "Burgundy", "Navy", "Midnight Blue", "Black", "Silver", "Pewter", "Teal", "Emerald", "Purple", "Violet", "Mint", "Sage"],
    avoid_colors: [],
    fabrics_perfect: ["Fine Corduroy", "Metallic fabrics", "Velvet", "Crystal embellished"],
    fabrics_good: ["Lace", "Eyelet", "Denim", "Tulle", "Satin", "Silk"],
    fabrics_avoid: [],
    prints: ["Paisley", "Leopard with flowers", "Geometric", "Tropical flowers", "Silver hearts", "William Morris designs"],
    silhouettes: ["Safari", "Striped resort", "Chanel style", "A-line", "Pencil skirts", "Princess cut"],
    jewelry_metals: ["White Gold", "Silver", "Rose Gold", "Platinum"],
    jewelry_stones: ["Diamonds", "Emeralds", "Sapphires", "Rubies", "Green Glass"],
    jewelry_styles: ["Hearts", "Lockets", "Etched silver", "Enamel", "Pave", "Floral motifs"],
    eras: ["Modern", "Chanel era"],
    artists: ["Matisse", "Picasso"],
    designers: ["Chanel", "Bluemarine", "Chloe"],
    makeup_lip: ["Raspberry", "Pink"],
    makeup_cheek: ["Pink", "Rose"],
    makeup_eye: ["Bottle green", "Emerald"],
    best_for: ["Winter galas", "Crystal-inspired events"],
  },
  {
    slug: "exotic-winter",
    name: "Exotic Winter",
    season: "winter",
    time_period: "mid",
    description: "Exotic palace with Persian and Moroccan influences",
    palette_effect: "Exotic Palace",
    key_colors: ["Rose Terra Cotta", "Terra Cotta", "Apricot", "Cream", "Wine", "Burgundy", "Deep Red", "Scarlet", "Black", "Blue-Black", "Midnight Blue", "Charcoal", "Deep Purple", "Emerald", "Teal", "Peacock Blue", "Cobalt", "Sapphire"],
    avoid_colors: [],
    fabrics_perfect: ["Silk Shantung", "Brocade", "Velvet", "Satin", "Metallic weave"],
    fabrics_good: ["Sari silk", "Embroidered silk", "Jacquard", "Tapestry", "Fine wool", "Cashmere"],
    fabrics_avoid: [],
    prints: ["Paisley", "Persian designs", "Moroccan patterns", "Ethnic prints", "Tile patterns", "Mosaic", "Peacocks", "Dragons"],
    silhouettes: ["Kaftan", "Sari inspired", "Column dress", "Draped silhouettes"],
    jewelry_metals: ["Antique Gold", "Gold", "Copper", "Bronze"],
    jewelry_stones: ["Jade", "Lapis Lazuli", "Turquoise", "Coral", "Amber", "Emeralds", "Rubies"],
    jewelry_styles: ["Layered chains", "Coin necklaces", "Chandelier earrings", "Cuffs", "Statement rings"],
    eras: ["Persian", "Moroccan", "Indian"],
    artists: [],
    designers: [],
    makeup_lip: ["Deep red", "Wine"],
    makeup_cheek: ["Terracotta", "Bronze"],
    makeup_eye: ["Kohl", "Gold", "Bronze"],
    best_for: ["Exotic events", "Palace-inspired occasions"],
  },
  {
    slug: "multi-colored-winter",
    name: "Multi-Colored Winter",
    season: "winter",
    time_period: "mid",
    description: "Silk Road with Persian Palace and Byzantine influences",
    palette_effect: "Silk Road",
    key_colors: ["Coral-Terra Cotta", "Rose Terra Cotta", "Apricot", "Cream", "Coral", "Red Coral", "Vermillion", "Black", "Midnight Blue", "Black Olive", "Grey-Green", "Plum", "Raisin", "Sapphire Blue"],
    avoid_colors: [],
    fabrics_perfect: ["Silk Shantung", "Two-tone silk", "Sari", "Fine tweed"],
    fabrics_good: ["Wool jersey", "Boucle", "Fur", "Linen", "Lace", "Chiffon", "Crushed velvet", "Jacquard", "Brocade", "Leather"],
    fabrics_avoid: [],
    prints: ["Chevron", "Prince of Wales", "Pomegranates", "Orange-lemon trees", "Leopard", "Tropical birds", "Roses", "Paisley", "Tile mosaic"],
    silhouettes: ["Kimono", "Sari", "Safari", "Asymmetrical", "Wrap", "Column", "Cape", "Kaftan"],
    jewelry_metals: ["Gold", "Platinum", "Silver", "Antique Gold"],
    jewelry_stones: ["Diamonds", "Emeralds", "Sapphires", "Coral", "Jade", "Blue Topaz", "Tourmaline", "Opal"],
    jewelry_styles: ["Braided gold", "Ropes", "Tassels", "Feather motifs", "Pearls", "Gold filigree", "Layered bangles"],
    eras: ["Ancient Chinese-Japanese", "Italian-Spanish classical", "1920's-1940's", "Persian-Indian"],
    artists: ["Vermeer", "Sargent", "Da Vinci"],
    designers: [],
    makeup_lip: ["Red", "Coral"],
    makeup_cheek: ["Terracotta"],
    makeup_eye: ["Sage", "Olive", "Emerald", "Sapphire"],
    best_for: ["Multi-cultural events", "Exotic occasions"],
  },
  {
    slug: "ornamental-winter",
    name: "Ornamental Winter",
    season: "winter",
    time_period: "mid",
    description: "Soft and rich earth tones, deep greens and blues with bright high notes in blue and purple",
    palette_effect: "Winter Sunset",
    key_colors: ["Rose-Terra Cotta", "Dusty Peach", "Dark Rose", "Ivory-Cream", "Apricot", "Burgundy", "Soft Red", "Sangria", "Midnight Blue", "Dark Blue", "Chocolate Brown", "Maroon", "Deep Purple", "Deep Teal", "Sea Green", "Sapphire", "Peacock Blue", "Royal Blue"],
    avoid_colors: [],
    fabrics_perfect: ["Silk", "Satin", "Velvet", "Brocade", "Silk weaves"],
    fabrics_good: ["Chiffon", "Fine Lace", "Wool Jersey", "Cotton-Linen", "Cashmere", "Soft Leather", "Suede"],
    fabrics_avoid: [],
    prints: ["Paisley", "Houndstooth", "Fine Check", "Abstract prints", "Houses, bridges, trees prints", "Animal Prints with Deer", "Roses", "Lilies", "Orchids"],
    silhouettes: ["Grecian Pleats", "Wrap dresses", "A line", "Column", "Safari", "Sari", "Kaftan", "Kimono"],
    jewelry_metals: ["Gold", "Silver", "Platinum", "Antique Gold"],
    jewelry_stones: ["Diamonds", "Amber", "Topaz", "Emeralds", "Sapphires", "Jade", "Turquoise"],
    jewelry_styles: ["Links", "Chains", "Filigree", "Chinese Lacquer", "Enamel", "Beaded Indian designs"],
    eras: ["1800's Italian", "1800's Moroccan", "Ancient Chinese", "Ancient Grecian"],
    artists: ["Modigliani", "Da Vinci", "Corot"],
    designers: [],
    makeup_lip: ["Mauves", "Reds"],
    makeup_cheek: ["Mauves", "Rose"],
    makeup_eye: ["Blues", "Greens", "Purples"],
    best_for: ["Ornamental events", "Formal occasions"],
  },
  {
    slug: "silk-road-winter",
    name: "Silk Road Winter",
    season: "winter",
    time_period: "mid",
    description: "Silk Road Traveler with Persian Palace and Chinese Dynasty influences",
    palette_effect: "Silk Road Traveler",
    key_colors: ["Rose Terra Cotta", "Terra Cotta", "Apricot", "Cream", "Ivory", "Wine", "Burgundy", "Deep Red", "Coral Red", "Black", "Midnight Blue", "Midnight Green", "Charcoal", "Olive", "Deep Purple", "Emerald", "Teal", "Peacock Blue", "Cobalt", "Sapphire"],
    avoid_colors: [],
    fabrics_perfect: ["Silk Shantung", "Brocade", "Damask", "Velvet", "Satin", "Metallic weave"],
    fabrics_good: ["Sari silk", "Embroidered silk", "Jacquard", "Tapestry", "Fine wool", "Cashmere", "Pashmina"],
    fabrics_avoid: [],
    prints: ["Paisley", "Persian designs", "Chinese motifs", "Silk Road patterns", "Tile patterns", "Mosaic", "Pagodas", "Dragons", "Phoenixes"],
    silhouettes: ["Kaftan", "Sari inspired", "Kimono", "Column dress", "Wrap dress", "Draped silhouettes"],
    jewelry_metals: ["Antique Gold", "Gold", "Copper", "Bronze"],
    jewelry_stones: ["Jade", "Lapis Lazuli", "Turquoise", "Coral", "Amber", "Emeralds", "Rubies"],
    jewelry_styles: ["Layered chains", "Coin necklaces", "Chandelier earrings", "Cuffs", "Statement rings", "Ethnic inspired"],
    eras: ["Persian", "Chinese Dynasty", "Moroccan Night", "Byzantine"],
    artists: [],
    designers: [],
    makeup_lip: ["Wine", "Deep red"],
    makeup_cheek: ["Bronze", "Terracotta"],
    makeup_eye: ["Kohl", "Gold", "Bronze"],
    best_for: ["Silk Road events", "Eastern-inspired occasions"],
  },
  {
    slug: "tapestry-winter",
    name: "Tapestry Winter",
    season: "winter",
    time_period: "mid",
    description: "Italian Renaissance with Mediterranean Princess and Biblical designs",
    palette_effect: "Italian Renaissance",
    key_colors: ["Brown-Mauve", "Pink-Mauve", "Dark Apricot", "Ivory", "Maroon", "Burgundy", "Mauve-Red", "Purple", "Grape", "Black", "Blue-Black", "Midnight Blue", "Charcoal Grey", "Grey Purple", "Olive", "Prussian Blue", "Teal", "Emerald Green", "Peacock Blue", "Cobalt Blue"],
    avoid_colors: [],
    fabrics_perfect: ["Silk shantung", "Silk wool blend", "Velvet", "Cut velvet", "Lace"],
    fabrics_good: ["Jersey", "Cashmere", "Fine knits", "Leather", "Suede", "Satin", "Denim", "Brocade", "Tapestry"],
    fabrics_avoid: [],
    prints: ["Missoni Prints", "Leopard", "Stripes", "Small Checks", "Paisley", "Geometric", "Leaves", "Chinese Pagodas", "Roses", "Orchids"],
    silhouettes: ["Hourglass shape", "Romantic and Tailored", "Trapeze dresses", "Fine pleats", "A line Wrap dresses"],
    jewelry_metals: ["Antique Gold", "Silver", "Platinum", "Bronze"],
    jewelry_stones: ["Emeralds", "Diamonds", "Sapphires", "Topaz", "Labradorite", "Agate", "Jade", "Ivory"],
    jewelry_styles: ["Gold Coins", "Ropes", "Chains", "Links"],
    eras: ["Italian Renaissance", "Spanish Renaissance", "Biblical", "Mediterranean"],
    artists: ["Modigliani", "Da Vinci"],
    designers: ["Missoni", "Brunello Cuccinelli", "Chloe"],
    makeup_lip: ["Skin tones", "Romantic Colors"],
    makeup_cheek: ["Skin tones", "Romantic Colors"],
    makeup_eye: ["Blues", "Greens", "Purples"],
    best_for: ["Renaissance events", "Tapestry-inspired occasions"],
  },
  {
    slug: "winter-rose",
    name: "Winter Rose",
    season: "winter",
    time_period: "early",
    description: "Winter Rose Garden with Snow Queen and Victorian Winter elegance",
    palette_effect: "Winter Rose Garden",
    key_colors: ["Rose", "Pink Rose", "Cream", "Porcelain", "Ivory", "Wine", "Burgundy", "Deep Rose", "Claret", "Raspberry", "Black", "Navy Blue", "Midnight Blue", "Charcoal", "Silver Grey", "Pewter", "Emerald", "Teal", "Sapphire", "Cobalt", "Lavender", "Ice Blue", "Mint"],
    avoid_colors: [],
    fabrics_perfect: ["Velvet", "Satin", "Fine Lace", "Chiffon", "Silk", "Cashmere"],
    fabrics_good: ["Fine Wool", "Brocade", "Organza", "Tulle", "Fur"],
    fabrics_avoid: [],
    prints: ["Roses", "Victorian florals", "Lace patterns", "Fine stripes", "Snowflakes", "Ribbons", "Pearls", "Cameos"],
    silhouettes: ["Princess style", "Victorian romantic", "Ice princess", "Elegant evening"],
    jewelry_metals: ["Silver", "White Gold", "Platinum", "Rose Gold"],
    jewelry_stones: ["Diamonds", "Sapphires", "Pearls", "Amethyst", "Blue Topaz", "Rose Quartz"],
    jewelry_styles: ["Filigree", "Victorian designs", "Delicate chains", "Pearl strands", "Lockets", "Cameos", "Snowflake motifs"],
    eras: ["Victorian Winter", "Romantic Winter"],
    artists: [],
    designers: [],
    makeup_lip: ["Deep wine", "Rose"],
    makeup_cheek: ["Rose", "Cream"],
    makeup_eye: ["Sapphire", "Emerald", "Soft grey"],
    best_for: ["Winter galas", "Rose-inspired events", "Victorian occasions"],
  },
];

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const results = {
      updated: 0,
      inserted: 0,
      errors: [] as string[],
    };

    for (const subtype of METHODOLOGY_SUBTYPES) {
      // Check if subtype exists
      const { data: existing } = await supabase
        .from("subtypes")
        .select("id, slug")
        .eq("slug", subtype.slug)
        .single();

      const subtypeRecord = {
        slug: subtype.slug,
        name: subtype.name,
        season: subtype.season,
        time_period: subtype.time_period || null,
        description: subtype.description || null,
        palette_effect: subtype.palette_effect || null,
        key_colors: subtype.key_colors,
        avoid_colors: subtype.avoid_colors,
        fabrics_perfect: subtype.fabrics_perfect,
        fabrics_good: subtype.fabrics_good,
        fabrics_avoid: subtype.fabrics_avoid,
        prints: subtype.prints,
        silhouettes: subtype.silhouettes,
        jewelry_metals: subtype.jewelry_metals,
        jewelry_stones: subtype.jewelry_stones,
        jewelry_styles: subtype.jewelry_styles,
        eras: subtype.eras,
        artists: subtype.artists,
        designers: subtype.designers,
        makeup_lip: subtype.makeup_lip,
        makeup_cheek: subtype.makeup_cheek,
        makeup_eye: subtype.makeup_eye,
        best_for: subtype.best_for,
        is_active: true,
      };

      if (existing) {
        // Update existing subtype
        const { error } = await supabase
          .from("subtypes")
          .update(subtypeRecord)
          .eq("id", existing.id);

        if (error) {
          results.errors.push(`Update ${subtype.slug}: ${error.message}`);
        } else {
          results.updated++;
        }
      } else {
        // Insert new subtype
        const { error } = await supabase
          .from("subtypes")
          .insert(subtypeRecord);

        if (error) {
          results.errors.push(`Insert ${subtype.slug}: ${error.message}`);
        } else {
          results.inserted++;
        }
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        message: `Synced ${results.updated + results.inserted} subtypes from methodology source`,
        details: {
          updated: results.updated,
          inserted: results.inserted,
          total_in_source: METHODOLOGY_SUBTYPES.length,
          errors: results.errors.length > 0 ? results.errors : undefined,
        },
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "Unknown error";
    console.error("Sync error:", err);
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
